version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: itinerary-admin
      MONGO_INITDB_ROOT_PASSWORD: 1234-admin
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
